// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olimp.Entities;

#nullable disable

namespace Olimp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Olimp.Entities.EduOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EduOrgs");
                });

            modelBuilder.Entity("Olimp.Entities.Olimp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Olimps");
                });

            modelBuilder.Entity("Olimp.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EduOrgId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OlimpId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EduOrgId");

                    b.HasIndex("OlimpId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Olimp.Entities.Registration", b =>
                {
                    b.HasOne("Olimp.Entities.EduOrg", "EduOrg")
                        .WithMany()
                        .HasForeignKey("EduOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olimp.Entities.Olimp", "Olimp")
                        .WithMany()
                        .HasForeignKey("OlimpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EduOrg");

                    b.Navigation("Olimp");
                });
#pragma warning restore 612, 618
        }
    }
}
